# Generated by Django 5.1.2 on 2024-11-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('subject', models.CharField(choices=[('general', 'Consulta General'), ('technical', 'Soporte Técnico'), ('collaboration', 'Propuesta de Colaboración'), ('other', 'Otro')], max_length=20, verbose_name='asunto')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('is_read', models.BooleanField(default=False, verbose_name='leído')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
