# Generated by Django 5.1.2 on 2024-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presurgeryform',
            name='imc',
            field=models.FloatField(verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='presurgeryform',
            name='peso',
            field=models.FloatField(verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='presurgeryform',
            name='talla',
            field=models.FloatField(verbose_name='Talla (cm)'),
        ),
    ]
