# Generated by Django 5.1.2 on 2024-11-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_presurgeryform_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postduringsurgeryform',
            name='folio_hospitalizacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='post_surgery_form', serialize=False, to='website.presurgeryform', verbose_name='Folio Hospitalización'),
        ),
    ]
