# Generated by Django 5.1.2 on 2025-08-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_postduringsurgeryform_folio_hospitalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postduringsurgeryform',
            name='nombre_residente',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nombre del Residente'),
        ),
    ]
